micronaut:
  application:
    name: apiRentalRvs
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'Elephant'
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa:
  default:
    packages-to-scan:
      - 'com.bateivo.tasks.dto'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
netty:
  default:
    allocator:
      max-order: 3
flyway:
  datasources:
    default:
      enabled: true
endpoints:
  flyway:
    enabled: true
    sensitive: false
